### ISSUE TITLE
19/01 - Ruby no cenário do mercado goiano

### ISSUE THREAD

**Issue by juuh42dias** [Guru-goias/meetups#1]
**Título**: _Ruby no cenário do mercado goiano_ 

**Descrição**:
A ideia deste primeiro meetup é de fazermos uma roda de conversa para falarmos a respeito da nossa situação no mercado goiano, conhecer empresas e desenvolvedores(as) de Goiânia e região.

**Data/Horário**: 19/01 ás 14h
**Local**: [Supera Tecnologia](https://goo.gl/maps/SAjmB6aZrs62) - Goiânia, Goiás
**Inscrição**: https://ev.congressy.com/ruby-e-o-cenario-do-mercado-goiano/
[**Código de Conduta**](https://www.codamos.club/PDF-C%C3%B3digo%20de%20Conduta.pdf)

**Apoiadores**: 
[_Credere_](https://meucredere.com.br/)
[_Supera Tecnologia_](https://www.supera.com.br/)

**Comment by henriquehsilva** [comment]
Ai sim hein...

**Comment by juuh42dias** [comment]
Obrigada pela presença pessoal, já temos data e local para o próximo Guru-GO, que será dia 16/02 no Sebrae. Em breve divulgo o tema/conteúdo do próximo. ☺️👩‍💻
