### ISSUE TITLE
02/04 - WIP: Quarentena Ruby

### ISSUE THREAD

**Issue by juuh42dias** [Guru-goias/meetups#3]
**Título**: Quarentena Ruby

**Descrição**:
[wip]

**Data/Horário**: 00/04 ás 19h
**Local**: --
**Código de Conduta**:
https://www.codamos.club/PDF-C%C3%B3digo%20de%20Conduta.pdf

**Apoiadores**:
[juliana.dev](https://juliana.dev)

**Comment by caiodsc** [comment]
Boa!

**Comment by marceloperini** [comment]
Queria falar sobre Form Objects, posso apresentar uma palestra.

**Comment by marceloperini** [comment]
@juuh42dias porque fechou?
